# Generated by Django 4.1.3 on 2023-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
