# Generated by Django 4.1.3 on 2023-10-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
